### ISSUE TITLE
IPv6 requests support

### ISSUE THREAD

**Issue by maaaaz** [JustinAzoff/python-cymruwhois#10]
Hello @JustinAzoff,

Thanks for this package.
It works great for IPv4 requests, but not for IPv6 (contrary to capacities shown on https://asn.cymru.com/cgi-bin/whois.cgi):
```
>>> import socket
>>> import cymruwhois

>>> cymru_resolver = cymruwhois.Client()

>>> socket.getaddrinfo("google.com", None, socket.AF_INET6)
[(<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('2a00:1450:4007:810::200e', 0, 0, 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('2a00:1450:4007:810::200e', 0, 0, 0)), (<AddressFamily.AF_INET6: 10>, <SocketKind.SOCK_RAW: 3>, 0, '', ('2a00:1450:4007:810::200e', 0, 0, 0))]

>>> socket.getaddrinfo("google.com", None, socket.AF_INET6)[0][4][0]
'2a00:1450:4007:80b::200e'

>>> d = socket.getaddrinfo("google.com", None, socket.AF_INET6)[0][4][0]

>>> vars(cymru_resolver.lookup(d))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/venvs/venvredflagpub/lib/python3.11/site-packages/cymruwhois.py", line 190, in lookup
    return list(self.lookupmany([ip]))[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/venvs/venvredflagpub/lib/python3.11/site-packages/cymruwhois.py", line 201, in lookupmany
    for rec in self._lookupmany_raw(not_cached):
  File "/root/venvs/venvredflagpub/lib/python3.11/site-packages/cymruwhois.py", line 232, in _lookupmany_raw
    r=asrecord(*parts)
      ^^^^^^^^^^^^^^^^
TypeError: asrecord.__init__() missing 2 required positional arguments: 'cc' and 'owner'
```

Any plan to support IPv6 ?

Cheers!

**Comment by maaaaz** [comment]
Nevermind, by instanciating a new `cymru_resolver = cymruwhois.Client()`, IPv6 worked!
