### ISSUE TITLE
Does not work with Python 3?

### ISSUE THREAD

**Issue by bortzmeyer** [JustinAzoff/python-cymruwhois#4]
```

% python3
Python 3.4.2 (default, Oct  8 2014, 13:14:40) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cymruwhois
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2222, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2164, in _find_spec
  File "<frozen importlib._bootstrap>", line 1940, in find_spec
  File "<frozen importlib._bootstrap>", line 1916, in _get_spec
  File "<frozen importlib._bootstrap>", line 1897, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 863, in spec_from_loader
  File "<frozen importlib._bootstrap>", line 904, in spec_from_file_location
  File "/usr/local/lib/python3.4/dist-packages/cymruwhois-1.0-py3.4.egg/cymruwhois.py", line 110
    except socket.error, e:
                       ^
SyntaxError: invalid syntax
```

Does it mean it does not work with Python 3? I find nothing in the documentation.

**Comment by bortzmeyer** [comment]
I tried the git HEAD with Python 3 and it worked (my first test was with the latest released version). Is there a released version for Python 3?

**Comment by JustinAzoff** [comment]
You are correct.. HEAD works with python 3.  I just bumped the version to 1.5 and tagged that, so you could use https://github.com/JustinAzoff/python-cymruwhois/archive/1.5.tar.gz  as a package url..

Unfortunately I haven't used PyPi in a while and don't remember my password.  Also, I think I was an idiot when I registered and used the email address of my old job which I no longer have access to.. so getting that updated will be a little more difficult :-(

**Comment by JustinAzoff** [comment]
Sorry, I dropped the ball on this.

I just signed up for sourceforce and submitted a ticket to have my pypi email updates so I can reset the password and finally update the package!

**Comment by anarcat** [comment]
any progress on this?

**Comment by JustinAzoff** [comment]
Ugh, no.  I'm still waiting for the pypi people to reset my password.

**Comment by JustinAzoff** [comment]
Hi!

I *finally* got access to my pypi account again, and was able to upload the latest version of the package.

https://pypi.python.org/pypi/cymruwhois should now install 1.6
